name: Automated SonyLIV JSON Updater

on:
  schedule:
    - cron: '*/7 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git User
        run: |
          git config --global user.name "sportlive18"
          git config --global user.email "271363488+sportlive18@users.noreply.github.com"

      - name: Sync and Update Log
        run: |
          export TZ="Asia/Kolkata"
          git pull origin main --rebase
          curl -sS -o sonyliv.json "https://raw.githubusercontent.com/drmlive/sliv-live-events/refs/heads/main/sonyliv.json"
          echo "🚀 SonyLIV Synced | IST: $(date +'%Y-%m-%d %H:%M:%S') | ID: $RANDOM" >> sliv.txt

      - name: Commit and Push
        run: |
          export TZ="Asia/Kolkata"
          git add sonyliv.json sliv.txt
          git diff --cached --quiet && echo "No changes to commit" && exit 0
          git commit -m "SonyLIV Database Updated ✅ [$(date +'%d-%m-%Y %H:%M')]"
          git push origin main
